### ISSUE TITLE
Linux版本直接会下到root里面

### ISSUE THREAD

**Issue by InfiniteLJH** [vscodev/asmr-downloader#2]
能不能也改成下载在当前目录，太头疼了

**Comment by vscodev** [comment]
默认就是下载在当前目录，你在哪里运行程序就会下载到哪里，下载到root里面说明你是在root目录下运行程序的。

**Comment by InfiniteLJH** [comment]
> 默认就是下载在当前目录，你在哪里运行程序就会下载到哪里，下载到root里面说明你是在root目录下运行程序的。

我放在usr它也是照样下到root里，哥们你试过吗？😓

**Comment by InfiniteLJH** [comment]
> 默认就是下载在当前目录，你在哪里运行程序就会下载到哪里，下载到root里面说明你是在root目录下运行程序的。

系统环境Ubuntu，试过n遍了。。。

**Comment by vscodev** [comment]
> > 默认就是下载在当前目录，你在哪里运行程序就会下载到哪里，下载到root里面说明你是在root目录下运行程序的。
> 
> 我放在usr它也是照样下到root里，哥们你试过吗？😓

跟程序所在目录无关，下载到哪仅取决于你运行程序时所处的目录，你可以在终端执行命令 `pwd` 查看你当前目录，若为 `/root` ，说明你当前是在 `/root` 目录下运行程序的，文件就会下载到 `/root` 目录下。
